repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9  # pick the latest release
    hooks:
      - id: ruff
        args: [--fix]  # auto-fix simple issues
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - types-python-dateutil

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
