default:
  region: eu-west-1
  file_format: parquet
  log_level: INFO
  s3:
    bucket_name: household-finances
  auth:
    algorithm: HS256
    access_token_expire_minutes: 15
    refresh_token_expire_days: 7

dev:
  log_level: DEBUG
  s3:
    bucket_name: household-finances-dev
  auth:
    secret_key: dev-secret-key


test:
  log_level: INFO
  s3:
    bucket_name: household-finances-test
  auth:
    secret_key: test-secret-key


prod:
  s3:
    bucket_name: household-finances
  auth:
    secret_key: ${SECRET_KEY}
  log_level: WARNING
