name: Build & Push (dev)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write    # for OIDC
  contents: read

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: "378779692580"
  ECR_REPO: household-finances
  IMAGE_TAG: dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::378779692580:role/gha-app-household-finances
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (linux/amd64)
        run: |
          IMAGE="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
          docker buildx build \
            --platform linux/amd64 \
            -t "$IMAGE" \
            --push \
            .
          echo "Pushed: $IMAGE"
